export const SET_PLACES = 'SET_PLACES';
export const GET_PLACES = 'GET_PLACES';
export const PLACE_ADDED = 'PLACE_ADDED';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const START_DELETE_PLACE = 'START_DELETE_PLACE';
export const START_ADD_PLACE = 'START_ADD_PLACE';

export const UI_START_LOADING = 'UI_START_LOADING';

export const UI_STOP_LOADING = 'UI_STOP_LOADING';

export const AUTH_TRY_AUTH = 'AUTH_TRY_AUTH';
export const AUTH_TRY_AUTO_SIGN_IN = 'AUTH_TRY_AUTO_SIGN_IN';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
export const AUTH_START_LOG_OUT = 'AUTH_START_LOG_OUT';
// export const AUTH_TRY_AUTH = 'AUTH_TRY_AUTH';

